import React, { useEffect, useState } from "react";
import api from "../../api/axios";
import {
  DownloadIcon,
  Clock3Icon,
  CoffeeIcon,
  TrendingUpIcon,
} from "lucide-react";

const DailyReport = () => {
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);

  // --------------------------------
  // Format seconds -> hours/minutes
  // --------------------------------
  const formatTime = (seconds = 0) => {
    const totalSeconds = Number(seconds) || 0;

    const totalMinutes = Math.floor(totalSeconds / 60);

    const hours = Math.floor(totalMinutes / 60);

    const minutes = totalMinutes % 60;

    if (hours > 0) {
      return `${String(hours).padStart(2, "0")}h ${String(
        minutes
      ).padStart(2, "0")}m`;
    }

    return `${minutes}m`;
  };

  // --------------------------------
  // Today's date
  // --------------------------------
  const getTodayDate = () => {
    return new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  };

  // --------------------------------
  // Normalize API response
  // --------------------------------
  const normalizeReport = (response) => {
    if (!response) {
      return null;
    }

    /*
      Possible backend responses:

      1.
      {
        activeTime: 100,
        idleTime: 20,
        breakTime: 120,
        productivity: 80
      }

      2.
      {
        activity: {
          activeTime: 100,
          idleTime: 20,
          breakTime: 120,
          productivity: 80
        }
      }

      3.
      {
        data: {
          activeTime: 100,
          ...
        }
      }

      4.
      {
        data: {
          activity: {
            ...
          }
        }
      }
    */

    if (response.activity) {
      return response.activity;
    }

    if (response.data?.activity) {
      return response.data.activity;
    }

    if (response.data) {
      return response.data;
    }

    return response;
  };

  // --------------------------------
  // Fetch today's activity
  // --------------------------------
  const fetchDailyReport = async () => {
    try {
      const res = await api.get("/activity/today");

      console.log("=================================");
      console.log("DAILY REPORT API RESPONSE:");
      console.log(res.data);
      console.log("=================================");

      const normalizedData = normalizeReport(res.data);

      console.log("NORMALIZED DAILY REPORT:");
      console.log(normalizedData);

      setReport(normalizedData);
    } catch (error) {
      console.log(
        "DAILY REPORT ERROR:",
        error.response?.data || error.message
      );

      setReport(null);
    } finally {
      setLoading(false);
    }
  };

  // --------------------------------
  // Initial load + auto refresh
  // --------------------------------
  useEffect(() => {
    fetchDailyReport();

    const interval = setInterval(() => {
      fetchDailyReport();
    }, 30000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  // --------------------------------
  // Download report
  // --------------------------------
  const downloadReport = () => {
    if (!report) {
      return;
    }

    const activeTime = formatTime(report.activeTime);
    const idleTime = formatTime(report.idleTime);
    const breakTime = formatTime(report.breakTime);

    const productivity = Number(report.productivity || 0);

    const reportText = `
DAILY EMPLOYEE PRODUCTIVITY REPORT
===================================

Date: ${getTodayDate()}

Active Time       : ${activeTime}
Idle Time         : ${idleTime}
Break Time        : ${breakTime}
Productivity      : ${productivity}%

Generated by Employee Workflow Tracking System
`;

    const blob = new Blob([reportText], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download = `Daily-Report-${new Date()
      .toISOString()
      .split("T")[0]}.txt`;

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  // --------------------------------
  // Values
  // --------------------------------
  const activeTime = Number(report?.activeTime || 0);

  const idleTime = Number(report?.idleTime || 0);

  const breakTime = Number(report?.breakTime || 0);

  const productiveTime = Number(report?.productiveTime || 0);

  const productivity = Number(report?.productivity || 0);

  // --------------------------------
  // Loading
  // --------------------------------
  if (loading) {
    return (
      <div className="rounded-3xl bg-white dark:bg-slate-900 shadow-xl p-6">
        <div className="py-10 text-center text-slate-500">
          Loading daily report...
        </div>
      </div>
    );
  }

 return (
  <div
    className="
    w-full
    rounded-3xl
    bg-white
    dark:bg-slate-900
    shadow-xl
    border
    border-slate-200
    dark:border-slate-800
    p-6
    mb-8
    "
  >

    {/* HEADER */}
    <div className="
      flex
      flex-col
      sm:flex-row
      sm:items-center
      sm:justify-between
      gap-4
      mb-6
    ">

      <div>
        <h2 className="
          text-xl
          font-bold
          text-slate-800
          dark:text-white
        ">
          Daily Report
        </h2>

        <p className="
          text-sm
          text-slate-500
          mt-1
        ">
          Auto-generated summary for today, {getTodayDate()}
        </p>
      </div>


      <button
        onClick={downloadReport}
        disabled={!report}
        className="
          flex
          items-center
          justify-center
          gap-2
          px-5
          py-2.5
          rounded-xl
          bg-indigo-600
          hover:bg-indigo-700
          text-white
          text-sm
          font-semibold
          transition
          disabled:opacity-50
        "
      >

        <DownloadIcon className="w-4 h-4"/>

        Download Report

      </button>


    </div>



    {
      !report ?

      (
        <div className="
          py-10
          text-center
          text-slate-500
        ">
          No activity data available for today.
        </div>
      )


      :

      (

      <>


      {/* STATS GRID */}

      <div className="
        grid
        grid-cols-1
        sm:grid-cols-2
        lg:grid-cols-4
        gap-5
      ">


        {/* ACTIVE */}

        <div className="
          rounded-2xl
          bg-emerald-50
          dark:bg-emerald-900/20
          p-5
        ">

          <div className="flex items-center gap-4">

            <div className="
              w-12
              h-12
              rounded-2xl
              bg-emerald-100
              flex
              items-center
              justify-center
              text-2xl
            ">
              ⏱️
            </div>


            <div>

              <p className="text-sm text-slate-500">
                Active
              </p>

              <h3 className="text-2xl font-bold">
                {formatTime(activeTime)}
              </h3>

            </div>

          </div>

        </div>




        {/* IDLE */}

        <div className="
          rounded-2xl
          bg-orange-50
          dark:bg-orange-900/20
          p-5
        ">

          <div className="flex items-center gap-4">

            <div className="
              w-12
              h-12
              rounded-2xl
              bg-orange-100
              flex
              items-center
              justify-center
              text-2xl
            ">
              💤
            </div>


            <div>

              <p className="text-sm text-slate-500">
                Idle
              </p>

              <h3 className="text-2xl font-bold">
                {formatTime(idleTime)}
              </h3>

            </div>


          </div>


        </div>





        {/* BREAK */}

        <div className="
          rounded-2xl
          bg-yellow-50
          dark:bg-yellow-900/20
          p-5
        ">


          <div className="flex items-center gap-4">


            <div className="
              w-12
              h-12
              rounded-2xl
              bg-yellow-100
              flex
              items-center
              justify-center
              text-2xl
            ">
              ☕
            </div>



            <div>

              <p className="text-sm text-slate-500">
                Break
              </p>

              <h3 className="text-2xl font-bold">
                {formatTime(breakTime)}
              </h3>


            </div>


          </div>


        </div>





        {/* PRODUCTIVITY */}

        <div className="
          rounded-2xl
          bg-indigo-50
          dark:bg-indigo-900/20
          p-5
        ">


          <div className="flex items-center gap-4">


            <div className="
              w-12
              h-12
              rounded-2xl
              bg-indigo-100
              flex
              items-center
              justify-center
              text-2xl
            ">
              📈
            </div>



            <div>

              <p className="text-sm text-slate-500">
                Productivity
              </p>


              <h3 className="
                text-2xl
                font-bold
                text-indigo-600
              ">
                {productivity}%
              </h3>


            </div>


          </div>


        </div>


      </div>





      {/* BOTTOM SUMMARY */}

      <div className="
        mt-6
        rounded-2xl
        bg-slate-50
        dark:bg-slate-800/50
        p-5
        grid
        grid-cols-1
        sm:grid-cols-2
        gap-4
      ">


        <div>

          <p className="text-sm text-slate-500">
            Productive Time
          </p>

          <h3 className="font-bold text-lg">
            {formatTime(productiveTime)}
          </h3>

        </div>



        <div>

          <p className="text-sm text-slate-500">
            Total Tracked
          </p>

          <h3 className="font-bold text-lg">
            {
              formatTime(
                activeTime +
                idleTime +
                breakTime
              )
            }
          </h3>

        </div>


      </div>


      </>

      )

    }


  </div>
);
};

export default DailyReport;